tap "adoptopenjdk/openjdk"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
tap "homebrew/services"
tap "neovim/neovim"
tap "sanemat/font"
brew "anyenv"
brew "autoconf"
brew "bat"
brew "libpng"
brew "freetype"
brew "libffi"
brew "openssl@1.1"
brew "pixman"
brew "cocoapods"
brew "coreutils"
brew "cscope"
brew "ctags"
brew "deno"
brew "exa"
brew "fd"
brew "gobject-introspection"
brew "icu4c"
brew "jpeg"
brew "ffmpeg"
brew "libtool"
brew "pango"
brew "fontforge"
brew "fzf"
brew "gh"
brew "gibo"
brew "git"
brew "git-delta"
brew "git-lfs"
brew "global"
brew "jq"
brew "lua"
brew "luajit", args: ["HEAD"]
brew "ruby"
brew "mas"
brew "mkcert"
brew "mycli"
brew "neovim", args: ["HEAD"]
brew "pwgen"
brew "ripgrep"
brew "ruby-build"
brew "thefuck"
brew "tig"
brew "tmux"
brew "tree"
brew "watchman"
brew "zsh"
brew "sanemat/font/ricty"
cask "alacritty"
cask "alfred"
cask "android-studio"
cask "deepl"
cask "dropbox"
cask "font-hack-nerd-font"
cask "google-chrome"
cask "google-japanese-ime"
cask "insomnia"
cask "iterm2"
cask "microsoft-teams"
cask "ngrok"
cask "react-native-debugger"
cask "runjs"
cask "skype"
cask "tableplus"
cask "typora"
cask "visual-studio-code"
cask "zoomus"
mas "GarageBand", id: 682658836
mas "iMovie", id: 408981434
mas "Keynote", id: 409183694
mas "Kindle", id: 405399194
mas "LadioCast", id: 411213048
mas "Numbers", id: 409203825
mas "Pages", id: 409201541
mas "PicGIF Lite", id: 844918735
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
