#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

#======================
# colorscheme
#======================
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'lifepillar/vim-solarized8'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sjl/badwolf'

[[plugins]]
repo = 'cocopon/iceberg.vim'
