#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

#======================
# colorscheme
#======================
[[plugins]]
repo = 'cocopon/iceberg.vim'
hook_add = '''
  set background=dark
  set termguicolors
  au Plugin_Hook VimEnter * ++nested colorscheme iceberg
'''
