#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
depends = ['neomru.vim']
on_cmd = 'Denite'
if = 'has("nvim")'
hook_source = 'source ~/.config/nvim/vimrc.d/plugins/denite.vim'

[[plugins]]
repo = "tpope/vim-fugitive"
hook_add = 'source ~/.config/nvim/vimrc.d/plugins/fugitive.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.config/nvim/vimrc.d/plugins/lightline.vim'

#======================
# colorscheme
#======================
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sjl/badwolf'
