#!/usr/bin/env zsh

function main() {
  emulate -L zsh
  setopt aliases
  local -a global_aliases=(${(@f)"$(alias -g)"})
  local -a characters=(${global_aliases%%\=*})
  if (($characters[(I)${(q)LBUFFER##* }])); then
     zle _expand_alias
     zle expand-word
  fi  
  zle self-insert
}

main
