#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
name = 'unite'
repo = 'Shougo/unite.vim'

[[plugins]]
name = 'neomru'
repo = 'Shougo/neomru.vim'
depends = ['unite']

[[plugins]]
name = 'neocomplete'
repo = 'Shougo/neocomplete.vim'

[[plugins]]
name = 'neosnippet'
repo = 'Shougo/neosnippet'

[[plugins]]
name = 'neosnippet-snippets'
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
name = 'vimfiler'
repo = 'Shougo/vimfiler'

[[plugins]]
name = 'vimshell'
repo = 'Shougo/vimshell.vim'

[[plugins]]
name = 'vimproc'
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
name = 'quickrun'
repo = 'thinca/vim-quickrun'

[[plugins]]
name = 'lightline'
repo = 'itchyny/lightline.vim'

[[plugins]]
name = 'fugitive'
repo = 'tpope/vim-fugitive'
