#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
name = 'unite.vim'
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite']

[[plugins]]
name = 'neocomplete.vim'
repo = 'Shougo/neocomplete.vim'

[[plugins]]
name = 'neosnippet.vim'
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
name = 'vimfiler.vim'
repo = 'Shougo/vimfiler'

[[plugins]]
name = 'vimshell.vim'
repo = 'Shougo/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
name = 'quickrun.vim'
repo = 'thinca/vim-quickrun'

[[plugins]]
name = 'lightline.vim'
repo = 'itchyny/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
