####################
##dein lazy setting
####################
[[plugins]]
repo = "davidhalter/jedi-vim"
on_ft = ['python']
build = 'git submodule update --init'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = ['go']

[[plugins]]
repo = 'todesking/ruby_hl_lvar.vim'
on_ft = ['ruby']
