#======================
# basic
#======================
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'
hook_add = 'source ~/.vim/vimrc.d/plugins/unite.vim'

[[plugins]]
repo = 'Shougo/unite-outline'
depends = ['unite']
hook_add = 'source ~/.vim/vimrc.d/plugins/unite-outline.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
depends = ['unite']

[[plugins]]
repo = 'Shougo/neocomplete.vim'
hook_add = 'source ~/.vim/vimrc.d/plugins/neocomplete.vim'
on_i = ['1']

[[plugins]]
repo = 'Shougo/neosnippet'
hook_add = 'source ~/.vim/vimrc.d/plugins/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/vimfiler'
hook_add = 'source ~/.vim/vimrc.d/plugins/vimfiler.vim'

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = 'source ~/.vim/vimrc.d/plugins/vimshell.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = 'source ~/.vim/vimrc.d/plugins/quickrun.vim'

[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = 'source ~/.vim/vimrc.d/plugins/lightline.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'
hook_add = 'source ~/.vim/vimrc.d/plugins/fugitive.vim'

#======================
# colorscheme
#======================
[[plugins]]
repo = 'altercation/vim-colors-solarized'

[[plugins]]
repo = 'nanotech/jellybeans.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'sjl/badwolf'
